insert into Manufacturers values(1, 'Innova Champion Discs');
insert into Manufacturers values(2, 'Discraft');
insert into Manufacturers values(3, 'Dynamic Discs');
insert into Manufacturers values(4, 'MVP');
insert into Manufacturers values(5, 'Prodigy');
insert into Manufacturers values(6, 'Discmania');
insert into Manufacturers values(7, 'DGA');
insert into Manufacturers values(8, 'Westside Discs');

insert into Players values (24, 'Richard Wysocki', 1);
insert into Players values (21, 'Paul Mcbeth', 2);
insert into Players values (1, 'Adam Hammes', 2);
insert into Players values (15, 'Kevin Jones', 5);
insert into Players values (8, 'Chris Dickerson', 5);
insert into Players values (11, 'Garrett Gurthie', 1);
insert into Players values (22, 'Paul Ulibarri', 2);
insert into Players values (5, 'Calvin Heimburg', 1);
insert into Players values (2, 'Alden Harris', 5);
insert into Players values (13, 'James Conrad', 1);
insert into Players values (12, 'Gregg Barsby', 1);
insert into Players values (16, 'Matt Bell', 7);
insert into Players values (17, 'Matthew Orum', 5);
insert into Players values (10, 'Emerson Keith', 3);
insert into Players values (23, 'Raven Newsom', 4);
insert into Players values (14, 'Joel Freeman', 1);
insert into Players values (3, 'Benjamin Callaway', 2);
insert into Players values (19, 'Nikko Locastro', 8);
insert into Players values (4, 'Bradley Williams', 1);
insert into Players values (20, 'Mason Ford', 1);
insert into Players values (18, 'Nathan Queen', 1);
insert into Players values (7, 'Chandler Fry', 2);
insert into Players values (6, 'Casey White', 6);
insert into Players values (25, 'Terry Rothlisberger', 2);
insert into Players values (9, 'Eagle McMahon', 6);

insert into Tour_Events values(1, "Las Vegas Challenge", "Elite Series");
insert into Tour_Events values(2, "Waco Annual Charity Open", "Elite Series");
insert into Tour_Events values(3, "Jonesboro Open", "Elite Series");
insert into Tour_Events values(4, "San Francisco Open", "Elite Series");
insert into Tour_Events values(5, "Portland Open", "Elite Series");
insert into Tour_Events values(6, "Discraft Great Lakes Open", "Elite Series");
insert into Tour_Events values(7, "The Preserve Championship", "Elite Series");
insert into Tour_Events values(8, "Discraft Ledgestone Insurance Open", "Elite Series");
insert into Tour_Events values(9, "Idlewild Open", "Elite Series");
insert into Tour_Events values(10, "MVP Open", "Elite Series");
insert into Tour_Events values(11, "Green Mountain Championship", "Elite Series");
insert into Tour_Events values(12, "Disc Golf Pro Tour Championship", "Elite Series");
insert into Tour_Events values(13, "Texas State Championships", "National Tour");
insert into Tour_Events values(14, "Glass Blown Open", "National Tour");
insert into Tour_Events values(15, "Master's Cup", "National Tour");
insert into Tour_Events values(16, "Beaver State Fling", "National Tour");
insert into Tour_Events values(17, "Delaware Disc Golf Challenge", "National Tour");
insert into Tour_Events values(18, "Music City Open", "National Tour");

insert into Player_Stats values(1, 'Richard Wysocki', 88, 34, 1, 8);
insert into Player_Stats values(2, 'Paul Mcbeth', 84, 31, 1, NULL);
insert into Player_Stats values(3, 'Adam Hammes', 84, 36, 1, 10);
insert into Player_Stats values(4, 'Kevin Jones', 82, 29, 3, NULL);
insert into Player_Stats values(5, 'Chris Dickerson', 85, 25, 1, 11);
insert into Player_Stats values(6, 'Garrett Gurthie', 77, 13, 4, NULL);
insert into Player_Stats values(7, 'Paul Ulibarri', 85, 18, 4, NULL);
insert into Player_Stats values(8, 'Calvin Heimburg', 83, 31, 1, 8);
insert into Player_Stats values(9, 'Alden Harris', 81, 21, 6, NULL);
insert into Player_Stats values(10, 'James Conrad', 87, 34, 2, NULL);
insert into Player_Stats values(11, 'Gregg Barsby', 74, 28, 12, NULL);
insert into Player_Stats values(12, 'Matt Bell', 89, 33, 4, NULL);
insert into Player_Stats values(13, 'Matthew Orum', 86, 32, 4, NULL);
insert into Player_Stats values(14, 'Emerson Keith', 78, 22, 4, NULL);
insert into Player_Stats values(15, 'Raven Newsom', 82, 36, 4, NULL);
insert into Player_Stats values(16, 'Joel Freeman', 79, 25, 3, NULL);
insert into Player_Stats values(17, 'Benjamin Callaway', 81, 23, 4, NULL);
insert into Player_Stats values(18, 'Nikko Locastro', 76, 25, 1, 2);
insert into Player_Stats values(19, 'Bradley Williams', 86, 16, 3, NULL);
insert into Player_Stats values(20, 'Mason Ford', 81, 19, 17, NULL);
insert into Player_Stats values(21, 'Nathan Queen', 81, 21, 1, 12);
insert into Player_Stats values(22, 'Chandler Fry', 86, 30, 16, NULL);
insert into Player_Stats values(23, 'Casey White', 84, 17, 5, NULL);
insert into Player_Stats values(24, 'Terry Rothlisberger', 82, 19, 17, NULL);
insert into Player_Stats values(25, 'Eagle McMahon', 89, 33, 1, 6);


insert into Discs values(1, "Aviar", 1, 2, 3, 0, 1);
insert into Discs values(2, "Roc", 1, 4, 4, 0, 3);
insert into Discs values(3, "Mako3", 1, 5, 5, 0, 0);
insert into Discs values(4, "Thunderbird", 1, 9, 5, 0, 2);
insert into Discs values(5, "Destroyer", 1, 12, 5, -1, 3);
insert into Discs values(6, "Luna", 2, 3, 3, 0, 3);
insert into Discs values(7, "Zone", 2, 4, 3, 0, 3);
insert into Discs values(8, "Buzzz", 2, 5, 4, -1, 1);
insert into Discs values(9, "Raptor", 2, 9, 4, 0, 3);
insert into Discs values(10, "Nuke", 2, 13, 5, -1, 3);
insert into Discs values(11, "Emac Judge", 3, 2, 4, 0, 1);
insert into Discs values(12, "Harp", 3, 4, 3, 0, 3);
insert into Discs values(13, "Truth", 3, 5, 5, -1, 1);
insert into Discs values(14, "Felon", 3, 9, 3, 0, 4);
insert into Discs values(15, "Enforcer", 3, 12, 4, 0, 4);
insert into Discs values(16, "Envy", 4, 3, 3, 0, 2);
insert into Discs values(17, "Proxy", 4, 3, 3, -1, 1);
insert into Discs values(18, "Atom", 4, 3, 3, 0, 1);
insert into Discs values(19, "Pilot", 4, 2, 5, 0, 1);
insert into Discs values(20, "Wave", 4, 11, 5, -2, 2);
insert into Discs values(21, "PA-3", 5, 3, 4, 0, 1);
insert into Discs values(22, "M3", 5, 5, 5, -1, 2);
insert into Discs values(23, "M4", 5, 5, 5, -1, 1);
insert into Discs values(24, "H3 V2", 5, 11, 5, -1, 2);
insert into Discs values(25, "D2", 5, 12, 6, -1, 3);
insert into Discs values(26, "P2", 6, 2, 3, 0, 1);
insert into Discs values(27, "MD3", 6, 5, 5, 0, 1);
insert into Discs values(28, "FD3", 6, 9, 4, 0, 3);
insert into Discs values(29, "PD2", 6, 12, 4, 0, 4);
insert into Discs values(30, "DD3", 6, 12, 5, -1, 3);
insert into Discs values(31, "Steady", 7, 2, 3, 0, 1);
insert into Discs values(32, "Quake", 7, 5, 3, 0, 3);
insert into Discs values(33, "Pipeline", 7, 8, 5, 0, 2);
insert into Discs values(34, "Banzai", 7, 8, 4, 0, 3);
insert into Discs values(35, "Hypercane", 7, 13, 4, 0, 4);
insert into Discs values(36, "Maiden", 8, 3, 4, 0, 1);
insert into Discs values(37, "Shield", 8, 3, 3, 0, 1);
insert into Discs values(38, "Harp", 8, 4, 3, 0, 3);
insert into Discs values(39, "Warship", 8, 5, 6, 0, 1);
insert into Discs values(40, "Destiny", 8, 14, 6, -2, 3);
